# Generated by Django 2.1.5 on 2019-01-20 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_registry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='certificate_csr',
            field=models.TextField(blank=True, null=True),
        ),
    ]
