# Generated by Django 2.1.5 on 2019-01-26 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_registry', '0003_auto_20190126_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='device_architecture',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
