# Generated by Django 2.1.5 on 2019-01-26 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('device_registry', '0004_device_device_architecture'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_model', models.CharField(blank=True, max_length=128, null=True)),
                ('device_architecture', models.CharField(blank=True, max_length=32, null=True)),
                ('device_manufacturer', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='device',
            name='device_architecture',
        ),
        migrations.RemoveField(
            model_name='device',
            name='device_manufacturer',
        ),
        migrations.RemoveField(
            model_name='device',
            name='device_model',
        ),
        migrations.AddField(
            model_name='deviceinfo',
            name='engine',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='device_registry.Device'),
        ),
    ]
