# Generated by Django 2.1.5 on 2019-01-26 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device_registry', '0005_auto_20190126_1007'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deviceinfo',
            old_name='engine',
            new_name='device_id',
        ),
    ]
