# Generated by Django 2.1.5 on 2019-01-26 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_registry', '0006_auto_20190126_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceinfo',
            name='device_operating_system',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='deviceinfo',
            name='device_operating_system_version',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
