# Generated by Django 2.1.5 on 2019-01-26 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_registry', '0008_auto_20190126_1147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='ipv4_address',
        ),
        migrations.AddField(
            model_name='deviceinfo',
            name='ipv4_address',
            field=models.GenericIPAddressField(blank=True, null=True, protocol='IPv4'),
        ),
    ]
