# Generated by Django 2.1.7 on 2019-03-20 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_registry', '0011_portscan'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceinfo',
            name='trust_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
