# Generated by Django 2.1.7 on 2019-03-20 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_registry', '0011_portscan'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceinfo',
            name='distr_id',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='deviceinfo',
            name='distr_release',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
