# Generated by Django 2.1.7 on 2019-03-22 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_registry', '0012_auto_20190320_0058'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceinfo',
            name='detected_mirai',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
