# Generated by Django 2.1.7 on 2019-04-08 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device_registry', '0012_deviceinfo_trust_score'),
        ('device_registry', '0013_deviceinfo_detected_mirai'),
    ]

    operations = [
    ]
