# Generated by Django 2.1.7 on 2019-04-09 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device_registry', '0012_portscan_firewall_enabled'),
        ('device_registry', '0014_merge_20190408_1133'),
    ]

    operations = [
    ]
