# Generated by Django 2.1.7 on 2019-04-09 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('device_registry', '0015_merge_20190409_0834'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirewallState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(blank=True, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device_registry.Device')),
            ],
        ),
        migrations.RemoveField(
            model_name='portscan',
            name='firewall_enabled',
        ),
    ]
