# Generated by Django 2.1.7 on 2019-04-24 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_registry', '0016_auto_20190409_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='firewallstate',
            name='scan_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
