# Generated by Django 2.1.7 on 2019-04-30 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_registry', '0018_auto_20190426_0619'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='fallback_token',
            field=models.CharField(default='', editable=False, max_length=128),
        ),
    ]
