# Generated by Django 2.1.7 on 2019-05-02 04:35

import device_registry.models
from django.contrib.postgres.fields import JSONField
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device_registry', '0019_device_fallback_token'),
    ]

    operations = [

        migrations.AlterField(
            model_name='portscan',
            name='scan_info',
            field=device_registry.models.JsonFieldTransitionHelper(),
        ),

        migrations.AlterField(
            model_name='portscan',
            name='scan_info',
            field=JSONField(),
        ),
    ]
