# Generated by Django 2.1.7 on 2019-05-02 11:33

from django.contrib.postgres.fields import JSONField
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device_registry', '0022_auto_20190503_0656'),
    ]

    operations = [
        migrations.AddField(
            model_name='firewallstate',
            name='rules',
            field=JSONField(default=dict),
        ),
    ]
