# Generated by Django 2.1.7 on 2019-05-06 08:35

from django.db import migrations
from django.contrib.postgres.fields import JSONField


class Migration(migrations.Migration):

    dependencies = [
        ('device_registry', '0023_firewallstate_rules'),
    ]

    operations = [
        migrations.AddField(
            model_name='portscan',
            name='netstat',
            field=JSONField(default=list),
        ),
    ]
