# Generated by Django 2.1.7 on 2019-05-09 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device_registry', '0023_firewallstate_rules'),
    ]

    operations = [
    ]
