# Generated by Django 2.1.7 on 2019-05-12 19:34

from django.db import migrations, models
from django.contrib.postgres.fields import JSONField


class Migration(migrations.Migration):

    dependencies = [
        ('device_registry', '0024_fix_scan_info_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceinfo',
            name='app_armor_enabled',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deviceinfo',
            name='selinux_state',
            field=JSONField(default=dict),
        ),
    ]
