# Generated by Django 2.1.7 on 2019-05-13 16:40

from django.db import migrations
from django.contrib.postgres.fields import JSONField


class Migration(migrations.Migration):

    dependencies = [
        ('device_registry', '0024_fix_scan_info_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceinfo',
            name='logins',
            field=JSONField(default=dict),
        ),
    ]
