# Generated by Django 2.1.7 on 2019-05-06 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_registry', '0024_portscan_netstat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portscan',
            name='scan_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
