# Generated by Django 2.1.7 on 2019-05-06 09:05

from django.db import migrations
import jsonfield_compat.fields


class Migration(migrations.Migration):

    dependencies = [
        ('device_registry', '0025_auto_20190508_0253'),
    ]

    operations = [
        migrations.AddField(
            model_name='portscan',
            name='block_networks',
            field=jsonfield_compat.fields.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='portscan',
            name='block_ports',
            field=jsonfield_compat.fields.JSONField(default=list),
        ),
    ]
