# Generated by Django 2.1.7 on 2019-05-08 12:16

from django.db import migrations
import jsonfield_compat.fields


class Migration(migrations.Migration):

    dependencies = [
        ('device_registry', '0026_auto_20190508_0305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portscan',
            name='block_ports',
            field=jsonfield_compat.fields.JSONField(default=dict),
        ),
    ]
