# Generated by Django 2.1.7 on 2019-05-11 07:23

from django.db import migrations
from django.contrib.postgres.fields import JSONField


class Migration(migrations.Migration):

    dependencies = [
        ('device_registry', '0027_auto_20190509_0516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portscan',
            name='block_ports',
            field=JSONField(default=list),
        ),
    ]
