# Generated by Django 2.1.7 on 2019-05-12 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device_registry', '0028_auto_20190511_0723'),
        ('device_registry', '0024_fix_scan_info_content'),
    ]

    operations = [
    ]
