# Generated by Django 2.1.7 on 2019-05-14 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device_registry', '0029_merge_20190512_0628'),
        ('device_registry', '0025_deviceinfo_logins'),
    ]

    operations = [
    ]
