# Generated by Django 2.1.7 on 2019-05-14 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device_registry', '0030_merge_20190514_0932'),
        ('device_registry', '0025_auto_20190512_1934'),
    ]

    operations = [
    ]
