# Generated by Django 2.1.7 on 2019-05-25 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_registry', '0033_auto_20190517_0559'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='name',
            field=models.CharField(blank=True, max_length=36),
        ),
    ]
