# Generated by Django 2.1.7 on 2019-05-29 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device_registry', '0035_fix_missing_protocol_version'),
        ('device_registry', '0035_auto_20190528_1300'),
    ]

    operations = [
    ]
