# Generated by Django 2.1.7 on 2019-06-03 05:32

from django.db import migrations
from django.db import IntegrityError
import re


def make_vlid_credential_names(apps, schema_editor):
    count = 0
    Credential = apps.get_model('device_registry', 'Credential')
    re_conversion = re.compile(r"[^\w0-9_.\-:]", re.UNICODE)  # find all not "unicode alphanumerics and _-.:"
    for credential in Credential.objects.all():
        new_name = re.sub(re_conversion, '_', credential.name)
        if new_name != credential.name:
            credential.name = new_name
            try:
                credential.save()
            except IntegrityError:
                credential.name += "_{}".format(count)
                count += 1
                credential.save()

class Migration(migrations.Migration):

    dependencies = [
        ('device_registry', '0037_auto_20190602_1731'),
    ]

    operations = [
        migrations.RunPython(make_vlid_credential_names),
    ]
