# Generated by Django 2.1.7 on 2019-06-04 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_registry', '0038_auto_20190603_0532'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='agent_version',
            field=models.CharField(max_length=36, blank=True, null=True),
        ),
    ]
