# Generated by Django 2.1.7 on 2019-06-07 07:05

from django.db import migrations, models
import tagulous.models.fields
import tagulous.models.models


class Migration(migrations.Migration):

    dependencies = [
        ('device_registry', '0039_device_agent_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField()),
                ('count', models.IntegerField(default=0, help_text='Internal counter of how many times this tag is in use')),
                ('protected', models.BooleanField(default=False, help_text='Will not be deleted when the count reaches 0')),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
            },
            bases=(tagulous.models.models.BaseTagModel, models.Model),
        ),
        migrations.AlterUniqueTogether(
            name='tags',
            unique_together={('slug',)},
        ),
        migrations.AddField(
            model_name='credential',
            name='tags',
            field=tagulous.models.fields.TagField(_set_tag_meta=True, autocomplete_view='ajax-tags-autocomplete', blank=True, force_lowercase=True, help_text='Enter a comma-separated tag string', initial='', to='device_registry.Tags'),

        ),
        migrations.AddField(
            model_name='device',
            name='tags',
            field=tagulous.models.fields.TagField(_set_tag_meta=True, autocomplete_view='ajax-tags-autocomplete', blank=True, force_lowercase=True, help_text='Enter a comma-separated tag string', initial='', to='device_registry.Tags'),

        ),
    ]
