# Generated by Django 2.1.9 on 2019-06-11 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_registry', '0040_auto_20190610_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='claim_token',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='device',
            name='fallback_token',
            field=models.CharField(default='', max_length=128),
        ),
    ]
