# Generated by Django 2.1.9 on 2019-06-13 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device_registry', '0041_auto_20190611_1405'),
        ('device_registry', '0040_auto_20190607_0705'),
    ]

    operations = [
    ]
