# Generated by Django 2.1.9 on 2019-06-20 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device_registry', '0043_auto_20190620_0730'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tags',
            new_name='Tag',
        ),
    ]
