# Generated by Django 2.1.9 on 2019-06-21 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_registry', '0045_auto_20190621_0208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firewallstate',
            name='policy',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Allow by default'), (2, 'Block by default')], default=1),
        ),
    ]
