# Generated by Django 2.1.9 on 2019-06-21 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device_registry', '0046_auto_20190621_0603'),
        ('device_registry', '0045_auto_20190620_1707'),
    ]

    operations = [
    ]
