# Generated by Django 2.1.9 on 2019-06-24 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device_registry', '0047_merge_20190622_0343'),
        ('device_registry', '0047_merge_20190621_1304'),
    ]

    operations = [
    ]
