# Generated by Django 2.1.9 on 2019-06-24 12:01

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device_registry', '0048_merge_20190624_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceinfo',
            name='device_metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
    ]
