# Generated by Django 2.1.9 on 2019-07-02 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device_registry', '0048_meta_tags'),
        ('device_registry', '0045_auto_20190620_1707'),
    ]

    operations = [
    ]
