# Generated by Django 2.1.9 on 2019-07-01 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device_registry', '0049_deviceinfo_device_metadata'),
        ('device_registry', '0048_meta_tags'),
    ]

    operations = [
    ]
