# Generated by Django 2.1.9 on 2019-07-02 07:06

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device_registry', '0049_merge_20190702_0706'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceinfo',
            name='device_metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
    ]
