# Generated by Django 2.1.10 on 2019-07-16 12:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('device_registry', '0052_credential_data'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='credential',
            unique_together={('owner', 'name', 'linux_user')},
        ),
        migrations.RemoveField(
            model_name='credential',
            name='key',
        ),
        migrations.RemoveField(
            model_name='credential',
            name='value',
        ),
    ]
