# Generated by Django 2.1.10 on 2019-08-06 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device_registry', '0054_device_calculated_trust_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deviceinfo',
            name='trust_score',
        ),
    ]
