# Generated by Django 2.1.10 on 2019-09-09 11:28

import device_registry.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_registry', '0055_remove_deviceinfo_trust_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='DebPackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('version', models.CharField(max_length=128)),
                ('arch', models.CharField(choices=[(device_registry.models.DebPackage.Arch('i386'), 'i386'), (device_registry.models.DebPackage.Arch('amd64'), 'amd64'), (device_registry.models.DebPackage.Arch('armhf'), 'armhf'), (device_registry.models.DebPackage.Arch('all'), 'all')], max_length=16)),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='deb_packages_hash',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterUniqueTogether(
            name='debpackage',
            unique_together={('name', 'version', 'arch')},
        ),
        migrations.AddField(
            model_name='device',
            name='deb_packages',
            field=models.ManyToManyField(to='device_registry.DebPackage'),
        ),
    ]
