# Generated by Django 2.1.10 on 2019-08-30 10:48

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device_registry', '0055_remove_deviceinfo_trust_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='deb_packages',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
    ]
