# Generated by Django 2.2.5 on 2019-09-12 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_registry', '0056_auto_20190909_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='update_trust_score',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
