# Generated by Django 2.1.11 on 2019-08-08 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('device_registry', '0056_auto_20190808_0821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firewallstate',
            name='global_policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='device_registry.GlobalPolicy'),
        ),
    ]
