# Generated by Django 2.1.11 on 2019-08-08 12:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('device_registry', '0057_auto_20190808_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalpolicy',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
    ]
