# Generated by Django 2.1.10 on 2019-09-05 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_registry', '0057_auto_20190904_0750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='deb_packages_hash',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
