# Generated by Django 2.2.5 on 2019-09-14 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device_registry', '0058_globalpolicy_created'),
        ('device_registry', '0057_device_update_trust_score'),
    ]

    operations = [
    ]
