# Generated by Django 2.1.10 on 2019-09-08 04:52

import device_registry.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_registry', '0058_auto_20190905_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='debpackage',
            name='arch',
            field=models.CharField(choices=[(device_registry.models.DebPackage.Distro('debian'), 'debian'), (device_registry.models.DebPackage.Distro('raspbian'), 'raspbian'), (device_registry.models.DebPackage.Distro('ubuntu'), 'ubuntu')], default='i386', max_length=16),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='debpackage',
            unique_together={('name', 'version', 'distro')},
        ),
    ]
