# Generated by Django 2.2.5 on 2019-09-20 10:11

import device_registry.models
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_registry', '0058_auto_20190917_1245'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vulnerability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('package', models.CharField(max_length=64)),
                ('is_binary', models.BooleanField()),
                ('unstable_version', models.CharField(blank=True, max_length=64)),
                ('other_versions', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), blank=True, size=None)),
                ('urgency', models.CharField(choices=[(device_registry.models.Urgency(' '), ' '), (device_registry.models.Urgency('L'), 'L'), (device_registry.models.Urgency('M'), 'M'), (device_registry.models.Urgency('H'), 'H')], max_length=64)),
                ('remote', models.BooleanField(null=True)),
                ('fix_available', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='debpackage',
            name='source_name',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='debpackage',
            name='source_version',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
