# Generated by Django 2.2.5 on 2019-09-20 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_registry', '0059_auto_20190920_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='debpackage',
            name='processed',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='debpackage',
            name='vulnerabilities',
            field=models.ManyToManyField(to='device_registry.Vulnerability'),
        ),
        migrations.AlterField(
            model_name='vulnerability',
            name='package',
            field=models.CharField(db_index=True, max_length=64),
        ),
    ]
