# Generated by Django 2.2.5 on 2019-09-16 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_registry', '0059_merge_20190914_0551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalpolicy',
            name='name',
            field=models.CharField(max_length=32),
        ),
        migrations.AddConstraint(
            model_name='globalpolicy',
            constraint=models.UniqueConstraint(fields=('name', 'owner'), name='unique_name'),
        ),
    ]
