# Generated by Django 2.2.5 on 2019-09-30 10:09

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device_registry', '0060_auto_20190920_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceinfo',
            name='processes',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
    ]
