# Generated by Django 2.2.6 on 2019-10-14 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_registry', '0062_device_audit_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='debpackage',
            name='os_release_codename',
            field=models.CharField(default='stretch', max_length=64),
            preserve_default=False
        ),
        migrations.AddField(
            model_name='vulnerability',
            name='os_release_codename',
            field=models.CharField(db_index=True, default='stretch', max_length=64),
            preserve_default=False
        ),
        migrations.AlterUniqueTogether(
            name='debpackage',
            unique_together={('name', 'version', 'arch', 'os_release_codename')},
        ),
    ]
