# Generated by Django 2.2.6 on 2019-10-18 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_registry', '0064_auto_20191016_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='auto_upgrades',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
