# Generated by Django 2.2.5 on 2019-10-23 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_registry', '0066_device_snoozed_actions'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='mysql_root_access',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
