# Generated by Django 2.2.7 on 2019-11-12 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_registry', '0069_distro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debpackage',
            name='os_release_codename',
            field=models.CharField(db_index=True, max_length=64),
        ),
    ]
