# Generated by Django 2.2.7 on 2019-12-02 17:25

import device_registry.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('device_registry', '0071_auto_20191114_0853'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='snoozed_actions',
        ),
        migrations.CreateModel(
            name='RecommendedAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_id', models.PositiveSmallIntegerField()),
                ('snoozed', models.PositiveSmallIntegerField(choices=[(device_registry.models.RecommendedAction.Status(0), 0), (device_registry.models.RecommendedAction.Status(1), 1), (device_registry.models.RecommendedAction.Status(2), 2), (device_registry.models.RecommendedAction.Status(3), 3)], default=device_registry.models.RecommendedAction.Status(0))),
                ('snoozed_until', models.DateTimeField(null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device_registry.Device')),
            ],
        ),
    ]
