# Generated by Django 2.2.7 on 2019-12-02 17:32

import device_registry.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_registry', '0072_auto_20191202_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendedaction',
            name='snoozed',
            field=models.PositiveSmallIntegerField(choices=[(device_registry.models.RecommendedAction.Status(0), 0), (device_registry.models.RecommendedAction.Status(1), 1), (device_registry.models.RecommendedAction.Status(2), 2), (device_registry.models.RecommendedAction.Status(3), 3)], default=0),
        ),
        migrations.AlterField(
            model_name='recommendedaction',
            name='snoozed_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
