# Generated by Django 2.2.5 on 2019-12-19 06:32

import device_registry.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_registry', '0073_auto_20191202_1732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendedaction',
            name='snoozed',
        ),
        migrations.AddField(
            model_name='recommendedaction',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(device_registry.models.RecommendedAction.Status(0), 0), (device_registry.models.RecommendedAction.Status(1), 1), (device_registry.models.RecommendedAction.Status(2), 2), (device_registry.models.RecommendedAction.Status(3), 3), (device_registry.models.RecommendedAction.Status(4), 4)], default=0),
        ),
    ]
