# Generated by Django 2.2.6 on 2019-12-23 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device_registry', '0074_recommendedaction_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='recommendedaction',
            unique_together={('device', 'action_id')},
        ),
    ]
