# Generated by Django 2.2.6 on 2019-12-23 14:36

from django.db import migrations


def generate_recommended_actions(apps, schema_editor):
    from device_registry.models import Device
    for d in Device.objects.all():
        d.generate_recommended_actions()


class Migration(migrations.Migration):

    dependencies = [
        ('device_registry', '0074_recommendedaction_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='recommendedaction',
            unique_together={('device', 'action_id')},
        ),
        migrations.RunPython(generate_recommended_actions)
    ]
