# Generated by Django 2.2.6 on 2019-12-23 14:36

from django.db import migrations


def generate_recommended_actions(apps, schema_editor):
    from device_registry.models import RecommendedAction
    RecommendedAction.update_all_devices()


class Migration(migrations.Migration):

    dependencies = [
        ('device_registry', '0074_recommendedaction_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='recommendedaction',
            unique_together={('device', 'action_id')},
        ),
        migrations.RunPython(generate_recommended_actions)
    ]
