# Generated by Django 2.2.5 on 2019-12-24 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_registry', '0075_auto_20191223_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendedaction',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
