# Generated by Django 2.2.7 on 2020-01-01 18:44

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_registry', '0076_recommendedaction_resolved_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='default_password_users',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32), blank=True, null=True, size=None),
        ),
    ]
