# Generated by Django 2.2.5 on 2020-01-07 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device_registry', '0077_historyrecord'),
        ('device_registry', '0077_device_default_password_users'),
    ]

    operations = [
    ]
