# Generated by Django 2.2.9 on 2020-01-28 13:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('device_registry', '0079_vulnerability'),
    ]

    operations = [
    ]
