# Generated by Django 2.2.6 on 2020-01-22 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_registry', '0079_vulnerability'),
    ]

    operations = [
        migrations.AddField(
            model_name='historyrecord',
            name='cve_high_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='historyrecord',
            name='cve_low_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='historyrecord',
            name='cve_medium_count',
            field=models.IntegerField(null=True),
        ),
    ]
