# Generated by Django 2.2.5 on 2020-02-04 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('device_registry', '0080_history_cve_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceHistoryRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommended_actions_count', models.IntegerField(null=True)),
                ('sampled_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device_registry.Device')),
            ],
        ),
    ]
