# Generated by Django 2.2.5 on 2020-02-04 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device_registry', '0080_history_cve_count'),
        ('device_registry', '0080_auto_20200128_1317'),
    ]

    operations = [
    ]
