# Generated by Django 2.2.10 on 2020-02-21 13:01

from django.db import migrations, models
from django.db.models import Case, CharField, Value, When


def convert_action_id(apps, schema_editor):
    actions = {
        2: ('FirewallDisabledAction', None),
        7: ('FtpServerAction', None),
        1001: ('InsecureServicesAction', 'fingerd'),
        1002: ('InsecureServicesAction', 'tftpd'),
        1003: ('InsecureServicesAction', 'telnetd'),
        1004: ('InsecureServicesAction', 'snmpd'),
        1005: ('InsecureServicesAction', 'xinetd'),
        1006: ('InsecureServicesAction', 'nis'),
        1007: ('InsecureServicesAction', 'atftpd'),
        1008: ('InsecureServicesAction', 'tftpd-hpa'),
        1009: ('InsecureServicesAction', 'rsh-server'),
        1010: ('InsecureServicesAction', 'rsh-redone-server'),
        2004: ('OpensshIssueAction', 'AllowAgentForwarding'),
        2003: ('OpensshIssueAction', 'PasswordAuthentication'),
        2002: ('OpensshIssueAction', 'PermitRootLogin'),
        2001: ('OpensshIssueAction', 'PermitEmptyPasswords'),
        2005: ('OpensshIssueAction', 'Protocol'),
        6: ('AutoUpdatesAction', None),
        3001: ('PubliclyAccessibleServiceAction', 'mongod'),
        3002: ('PubliclyAccessibleServiceAction', 'mysqld'),
        3003: ('PubliclyAccessibleServiceAction', 'memcached'),
        3004: ('PubliclyAccessibleServiceAction', 'redis-server'),
        10: ('MySQLDefaultRootPasswordAction', None),
        12: ('CpuVulnerableAction', None),
        3: ('VulnerablePackagesAction', None)
    }
    RecommendedActionModel = apps.get_model('device_registry', 'RecommendedAction')
    RecommendedActionModel.objects.update(action_class=Case(
        *[When(action_id=k, then=Value(v[0])) for k, v in actions.items()],
    ), action_param=Case(
        *[When(action_id=k, then=Value(v[1])) for k, v in actions.items()],
    ))

    id_DefaultCredentialsAction = 1
    RecommendedActionModel.objects.filter(action_id=id_DefaultCredentialsAction).delete()


def update_default_credentials(apps, schema_editor):
    from device_registry.models import RecommendedAction
    from device_registry.recommended_actions import DefaultCredentialsAction
    RecommendedAction.update_all_devices(classes=[DefaultCredentialsAction])


class Migration(migrations.Migration):

    dependencies = [
        ('device_registry', '0082_devicehistoryrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendedaction',
            name='action_class',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recommendedaction',
            name='action_param',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='recommendedaction',
            unique_together={('device', 'action_class', 'action_param')},
        ),
        # migrations.RunPython(convert_action_id),
        migrations.RemoveField(
            model_name='recommendedaction',
            name='action_id',
        ),
        # migrations.RunPython(update_default_credentials),
    ]
