# Generated by Django 2.2.10 on 2020-02-25 12:44

import device_registry.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('device_registry', '0083_auto_20200221_1301'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='recommendedaction',
            unique_together={('action_class', 'action_param')},
        ),
        migrations.CreateModel(
            name='GithubIssue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, null=True)),
                ('number', models.IntegerField(default=0)),
                ('closed', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device_registry.RecommendedAction'))
            ],
        ),
        migrations.RemoveField(
            model_name='recommendedaction',
            name='device',
        ),
        migrations.RemoveField(
            model_name='recommendedaction',
            name='resolved_at',
        ),
        migrations.RemoveField(
            model_name='recommendedaction',
            name='snoozed_until',
        ),
        migrations.RemoveField(
            model_name='recommendedaction',
            name='status',
        ),
        migrations.CreateModel(
            name='RecommendedActionStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(choices=[(device_registry.models.RecommendedAction.Status(0), 0), (device_registry.models.RecommendedAction.Status(1), 1), (device_registry.models.RecommendedAction.Status(2), 2), (device_registry.models.RecommendedAction.Status(3), 3), (device_registry.models.RecommendedAction.Status(4), 4)], default=0)),
                ('snoozed_until', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device_registry.Device')),
                ('ra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device_registry.RecommendedAction')),
            ],
            options={
                'unique_together': {('device', 'ra')},
            },
        ),
    ]
