# Generated by Django 2.2.10 on 2020-03-02 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_registry', '0084_ra_remove_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubissue',
            name='affected',
            field=models.ManyToManyField(related_name='github_issues_affected', to='device_registry.Device'),
        ),
        migrations.AddField(
            model_name='githubissue',
            name='resolved',
            field=models.ManyToManyField(related_name='github_issues_resolved', to='device_registry.Device'),
        ),
    ]
