# Generated by Django 2.2.10 on 2020-03-16 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_registry', '0085_auto_20200302_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='claimed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
