# Generated by Django 2.2.10 on 2020-03-05 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_registry', '0085_auto_20200302_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debpackage',
            name='name',
            field=models.CharField(db_index=True, max_length=128),
        ),
    ]
