# Generated by Django 2.2.10 on 2020-03-14 05:07

import device_registry.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_registry', '0085_auto_20200302_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vulnerability',
            name='urgency',
            field=models.PositiveSmallIntegerField(choices=[(device_registry.models.Vulnerability.Urgency(0), 0), (device_registry.models.Vulnerability.Urgency(1), 1), (device_registry.models.Vulnerability.Urgency(2), 2), (device_registry.models.Vulnerability.Urgency(3), 3), (device_registry.models.Vulnerability.Urgency(4), 4)]),
        ),
    ]
