# Generated by Django 2.2.11 on 2020-03-18 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_registry', '0086_device_claimed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='claimed_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
