# Generated by Django 2.2.10 on 2020-03-06 17:02

from django.db import migrations, models

from device_registry.models import UBUNTU_SUITES, UBUNTU_KERNEL_PACKAGES_RE_PATTERN


def reset_kernel_packages_vulns(apps, schema_editor):
    # Delete vulns of kernel-related packages.
    DebPackageVulnerability = apps.get_model('device_registry', 'DebPackage').vulnerabilities.through
    # Ubuntu.
    DebPackageVulnerability.objects.filter(
        debpackage__os_release_codename__in=UBUNTU_SUITES, debpackage__name__regex=UBUNTU_KERNEL_PACKAGES_RE_PATTERN
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('device_registry', '0087_auto_20200318_0652'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='reboot_required',
            field=models.BooleanField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='vulnerability',
            name='name',
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='vulnerability',
            name='fix_available',
            field=models.BooleanField(db_index=True),
        ),
        migrations.RunPython(reset_kernel_packages_vulns)
    ]
