# Generated by Django 2.2.11 on 2020-03-23 10:08

from django.db import migrations, models


def update_default_credentials(apps, schema_editor):
    from device_registry.models import RecommendedActionStatus
    from device_registry.recommended_actions import AuditdNotInstalledAction
    RecommendedActionStatus.update_all_devices(classes=[AuditdNotInstalledAction])


class Migration(migrations.Migration):

    dependencies = [
        ('device_registry', '0088_auto_20200306_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debpackage',
            name='name',
            field=models.CharField(db_index=True, max_length=128),
        )
    ]
