# Generated by Django 2.2.11 on 2020-03-26 12:32

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device_registry', '0089_auto_20200323_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendedaction',
            name='action_context',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
    ]
