# Generated by Django 2.2.11 on 2020-03-26 12:32

import device_registry.recommended_actions
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


def update_ra(apps, schema_editor):
    from device_registry.models import RecommendedAction, RecommendedActionStatus
    RecommendedAction.objects.filter(action_class='VulnerablePackagesAction').delete()
    for ra in RecommendedAction.objects.all():
        action_class = device_registry.recommended_actions.ActionMeta.get_class(ra.action_class)
        param = ra.action_param
        ra.action_context = action_class.get_context(param)
        ra.action_severity = action_class.severity(param)
        ra.save(update_fields=['action_context', 'action_severity'])
    RecommendedActionStatus.update_all_devices([device_registry.recommended_actions.CVEAction])


class Migration(migrations.Migration):

    dependencies = [
        ('device_registry', '0089_auto_20200323_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendedaction',
            name='action_context',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='recommendedaction',
            name='action_severity',
            field=models.PositiveSmallIntegerField(choices=[(device_registry.recommended_actions.Severity(1), 1), (device_registry.recommended_actions.Severity(2), 2), (device_registry.recommended_actions.Severity(3), 3)], default=1),
            preserve_default=False,
        ),
        migrations.RunPython(update_ra)
    ]
