# Generated by Django 2.2.11 on 2020-03-25 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device_registry', '0089_auto_20200323_1008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firewallstate',
            name='policy',
        ),
    ]
