# Generated by Django 2.2.11 on 2020-03-31 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_registry', '0090_recommendedaction_action_context'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historyrecord',
            name='sampled_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
