# Generated by Django 2.2.11 on 2020-03-26 17:08

import device_registry.recommended_actions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_registry', '0090_recommendedaction_action_context'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendedaction',
            name='action_severity',
            field=models.PositiveSmallIntegerField(choices=[(device_registry.recommended_actions.Severity(1), 1), (device_registry.recommended_actions.Severity(2), 2), (device_registry.recommended_actions.Severity(3), 3)], default=1),
            preserve_default=False,
        ),
    ]
