# Generated by Django 2.2.11 on 2020-04-03 11:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def delete_history_record_duplicates(apps, schema_editor):
    Profile = apps.get_model('profile_page', 'Profile')
    for profile in Profile.objects.filter(user__devices__isnull=False).distinct().only('user'):
        dates = set()
        for hr in profile.user.history_records.order_by('pk'):
            if hr.sampled_at.date() in dates:
                hr.delete()
            else:
                dates.add(hr.sampled_at.date())


class Migration(migrations.Migration):
    dependencies = [
        ('device_registry', '0091_auto_20200331_1030'),
    ]

    operations = [
        migrations.RunPython(delete_history_record_duplicates),
        migrations.AlterField(
            model_name='historyrecord',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_records',
                                    to=settings.AUTH_USER_MODEL, unique_for_date='sampled_at'),
        )
    ]
