FROM python:3.7-slim-stretch as build
WORKDIR /usr/src/app

RUN apt-get update && \
    apt-get install -y --no-install-recommends build-essential libssl-dev libffi-dev libltdl-dev && \
    apt-get clean

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY backend ./

ENV DJANGO_SETTINGS_MODULE backend.settings.prod

RUN python manage.py collectstatic --noinput

FROM nginx:alpine

COPY ./conf/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /usr/src/app/backend/static/ /usr/share/nginx/html/
COPY --from=build /usr/src/app/backend/staticfiles/ /usr/share/nginx/html/

