FROM python-base as build

# This is such that we can override it during build
ARG DJANGO_SETTINGS_MODULE=backend.settings.prod
ENV DJANGO_SETTINGS_MODULE ${DJANGO_SETTINGS_MODULE}

RUN python3 manage.py collectstatic --noinput

FROM node:12 as webpack
WORKDIR /usr/src/app
RUN apt-get update && \
    apt-get install -y build-essential g++ libsass-dev python

COPY ./misc /usr/src/misc
COPY ./backend ./
COPY --from=build /usr/src/app/backend/staticfiles ./backend/staticfiles
RUN rm -rf node_modules && npm install
RUN npm run build

FROM nginx:alpine
COPY ./conf/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /usr/src/app/backend/static/ /usr/share/nginx/html/
COPY --from=build /usr/src/app/backend/staticfiles/ /usr/share/nginx/html/
COPY --from=webpack /usr/src/app/backend/static/ /usr/share/nginx/html/
COPY --from=webpack /usr/src/app/webpack-stats.json /usr/share/nginx/html/
