# Generated by Django 2.1.7 on 2019-06-05 10:12
from django.db import migrations
from django.contrib.auth.models import User

def make_lower_names(apps, schema_editor):
    count = 0
    User = apps.get_model('auth', 'User')
    users = User.objects.all()
    for user in users:
        print("processing user...{}".format(user.username))
        old_name = user.username
        if user.username.islower():
            print("ok")
            continue
        user.username = old_name.lower()
        while User.objects.filter(username=user.username).exists():
            user.username = "{}_{}".format(old_name.lower(), count)
            count += 1
        print("save {} as {}".format(old_name, user.username))
        user.save()
        print("ok")

class Migration(migrations.Migration):

    dependencies = [
        ('profile_page', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(make_lower_names)
    ]
