# Generated by Django 2.1.10 on 2019-07-08 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_page', '0003_auto_20190705_1446'),
        ('profile_page', '0003_profile_last_active'),
    ]

    operations = [
    ]
