# Generated by Django 2.1.10 on 2019-07-22 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_page', '0004_merge_20190708_0744'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='payment_plan',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Free'), (2, 'Standard'), (3, 'Professional'), (4, 'Enterprise')], default=1),
        ),
    ]
