# Generated by Django 2.2.6 on 2019-10-07 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_page', '0005_profile_payment_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='wizard_shown',
            field=models.BooleanField(default=False),
        ),
    ]
