# Generated by Django 2.2.6 on 2019-10-16 07:34

from django.db import migrations


def set_email_as_username(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    for user in User.objects.all():
        if user.email:
            user.username = user.email.lower()
            user.save()


class Migration(migrations.Migration):
    dependencies = [
        ('profile_page', '0006_profile_wizard_shown'),
    ]

    operations = [
        migrations.RunPython(set_email_as_username),
    ]
