# Generated by Django 2.2.6 on 2019-10-18 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_page', '0007_auto_20191016_0734'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='first_signin',
            field=models.BooleanField(default=False),
        ),
    ]
