# Generated by Django 2.2.6 on 2019-11-19 09:53

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_page', '0008_profile_first_signin'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='github_auth_code',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='profile',
            name='github_issues',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='profile',
            name='github_oauth_token',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='profile',
            name='github_random_state',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='profile',
            name='github_repo_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
