# Generated by Django 2.2.5 on 2019-11-20 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_page', '0009_profile_phone'),
        ('profile_page', '0009_auto_20191119_0953'),
    ]

    operations = [
    ]
