# Generated by Django 2.2.6 on 2019-11-22 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_page', '0009_profile_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='first_signin',
        ),
    ]
