# Generated by Django 2.2.6 on 2019-11-22 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_page', '0009_profile_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='first_signin',
            new_name='signed_in',
        ),
        migrations.AddField(
            model_name='profile',
            name='signed_up',
            field=models.BooleanField(default=False),
        ),
    ]
