# Generated by Django 2.2.5 on 2019-11-21 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_page', '0010_merge_20191120_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='github_repo_url',
            field=models.URLField(blank=True),
        ),
    ]
