# Generated by Django 2.2.5 on 2019-11-26 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_page', '0010_remove_profile_first_signin'),
        ('profile_page', '0010_profile_github_issues'),
    ]

    operations = [
    ]
