# Generated by Django 2.2.8 on 2019-12-05 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_page', '0011_merge_20191126_0607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='payment_plan',
        ),
    ]
