# Generated by Django 2.2.5 on 2019-11-22 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_page', '0011_profile_github_repo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='github_repo_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
